[project]
name = "marimotest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.14.10",
    "pandas>=2.3.1",
    "pyarrow>=20.0.0",
]
